name: test-action
on: workflow_dispatch
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: install @octokit/core
      - run: install libsodium-wrappers
      - run: node ghesecret.js
      
